/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e96f3a4a-21c9-4f78-968d-8ddc3247638f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZcxtGN0BO",
    "aws_user_pools_web_client_id": "m29qatoahbl83jpkvlsmqr3lq",
    "oauth": {
        "domain": "nejmafe2231e7f3-2231e7f3-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:7000/",
        "redirectSignOut": "http://localhost:7000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
export default awsmobile;